// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(FilamentDbContext))]
    [Migration("20260611120000_AddPrinterMqttCredentials")]
    partial class AddPrinterMqttCredentials
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
