// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(FilamentDbContext))]
    partial class FilamentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Domain.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Snapshot")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("Domain.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OfdSlug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Brands", (string)null);
                });

            modelBuilder.Entity("Domain.Models.FilamentCacheSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FilamentCacheSnapshots", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("Domain.Models.NfcTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SpoolId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpoolId");

                    b.HasIndex("TagUid")
                        .IsUnique();

                    b.ToTable("NfcTags", (string)null);
                });

            modelBuilder.Entity("Domain.Models.PrintJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<float>("GramsUsed")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FilamentDeducted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstimatedFinishTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrintFileName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrinterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SpoolId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId");

                    b.HasIndex("SpoolId");

                    b.ToTable("PrintJobs", (string)null);
                });

            modelBuilder.Entity("Domain.Models.PrintJobFilament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorName")
                        .HasColumnType("TEXT");

                    b.Property<float>("GramsUsed")
                        .HasColumnType("REAL");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrintJobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SpoolId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrintJobId");

                    b.HasIndex("SpoolId");

                    b.ToTable("PrintJobFilaments", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Printer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExtraSpoolId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Tray1SpoolId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Tray2SpoolId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Tray3SpoolId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Tray4SpoolId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExtraSpoolId");

                    b.HasIndex("Tray1SpoolId");

                    b.HasIndex("Tray2SpoolId");

                    b.HasIndex("Tray3SpoolId");

                    b.HasIndex("Tray4SpoolId");

                    b.ToTable("Printers", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Spool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BedMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BedMin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<float>("CurrentWeightG")
                        .HasColumnType("REAL");

                    b.Property<float?>("Density")
                        .HasColumnType("REAL");

                    b.Property<float?>("DiameterTolerance")
                        .HasColumnType("REAL");

                    b.Property<float>("InitialWeightG")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<float>("LowStockThresholdG")
                        .HasColumnType("REAL");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("StockLocation")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExtruderMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExtruderMin")
                        .HasColumnType("INTEGER");

                    b.Property<float>("SpoolWeightG")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Spools", (string)null);
                });

            modelBuilder.Entity("Domain.Models.SpoolProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("InitialWeightG")
                        .HasColumnType("REAL");

                    b.Property<float>("SpoolWeightG")
                        .HasColumnType("REAL");

                    b.Property<float>("LowStockThresholdG")
                        .HasColumnType("REAL");

                    b.Property<float?>("Density")
                        .HasColumnType("REAL");

                    b.Property<float?>("DiameterTolerance")
                        .HasColumnType("REAL");

                    b.Property<int?>("ExtruderMin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExtruderMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BedMin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BedMax")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SpoolProfiles", (string)null);
                });

            modelBuilder.Entity("Domain.Models.NfcTag", b =>
                {
                    b.HasOne("Domain.Models.Spool", "Spool")
                        .WithMany("NfcTags")
                        .HasForeignKey("SpoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spool");
                });

            modelBuilder.Entity("Domain.Models.PrintJob", b =>
                {
                    b.HasOne("Domain.Models.Printer", "Printer")
                        .WithMany("PrintJobs")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Spool", "Spool")
                        .WithMany("PrintJobs")
                        .HasForeignKey("SpoolId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Printer");

                    b.Navigation("Spool");
                });

            modelBuilder.Entity("Domain.Models.PrintJobFilament", b =>
                {
                    b.HasOne("Domain.Models.PrintJob", "PrintJob")
                        .WithMany("Filaments")
                        .HasForeignKey("PrintJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Spool", null)
                        .WithMany()
                        .HasForeignKey("SpoolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PrintJob");
                });

            modelBuilder.Entity("Domain.Models.Printer", b =>
                {
                    b.HasOne("Domain.Models.Spool", null)
                        .WithMany()
                        .HasForeignKey("ExtraSpoolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.Spool", null)
                        .WithMany()
                        .HasForeignKey("Tray1SpoolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.Spool", null)
                        .WithMany()
                        .HasForeignKey("Tray2SpoolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.Spool", null)
                        .WithMany()
                        .HasForeignKey("Tray3SpoolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.Spool", null)
                        .WithMany()
                        .HasForeignKey("Tray4SpoolId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Domain.Models.PrintJob", b =>
                {
                    b.Navigation("Filaments");
                });

            modelBuilder.Entity("Domain.Models.Printer", b =>
                {
                    b.Navigation("PrintJobs");
                });

            modelBuilder.Entity("Domain.Models.Spool", b =>
                {
                    b.Navigation("NfcTags");

                    b.Navigation("PrintJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
